groups:
  - name: intelligent_test_reporting_alerts
    rules:
      # 后端服务健康检查
      - alert: BackendServiceDown
        expr: up{job="backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "后端服务不可用"
          description: "后端服务已停止响应超过1分钟"

      # 前端服务健康检查
      - alert: FrontendServiceDown
        expr: up{job="frontend"} == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "前端服务不可用"
          description: "前端服务已停止响应超过2分钟"

      # 高错误率告警
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "HTTP错误率过高"
          description: "5分钟内HTTP 5xx错误率超过10%"

      # 响应时间过长
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "响应时间过长"
          description: "95%的请求响应时间超过2秒"

      # 内存使用率过高
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes / 1024 / 1024) > 500
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "内存使用率过高"
          description: "进程内存使用超过500MB"

      # 测试失败率过高
      - alert: HighTestFailureRate
        expr: (test_cases_failed / test_cases_total) > 0.2
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "测试失败率过高"
          description: "测试用例失败率超过20%"

      # 覆盖率过低
      - alert: LowTestCoverage
        expr: test_coverage_percentage < 70
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "测试覆盖率过低"
          description: "测试覆盖率低于70%"